// Franklin Finances - Dades Inicials (Catalan)
// Aquest fitxer conté els fons d'inversió inicials actius de la cartera.

window.FranklinDefaultData = {
  // Compte d'efectiu inicial en EUR
  cash: {
    balance: 15000.00, // en EUR
    currency: 'EUR'
  },
  
  // Objectius financers inicials
  goals: [
    {
      id: 'g_default_1',
      title: 'Fons d\'Emergència',
      target: 20000.00,
      deadline: '2026-12-31',
      category: 'Estalvi',
      notes: 'Fons de seguretat líquid equivalent a 6 mesos de despeses corrents.'
    },
    {
      id: 'g_default_2',
      title: 'Llibertat Financera',
      target: 1000000.00,
      deadline: '2040-12-31',
      category: 'Inversió',
      notes: 'Objectiu a llarg termini per viure de les rendes de la cartera.'
    }
  ],

  // Historial de transaccions inicials de Fons d'Inversió (considerant només l'Últim valor)
  transactions: [
    {
      id: 't_init_fons_1',
      date: '2025-12-01',
      type: 'compra',
      assetType: 'fons',
      isin: 'LU1353950725',
      symbol: 'AXA-GL',
      name: 'AXA WLD-GL INF SH DUR-AH',
      quantity: 1,
      price: 126209.00,
      commission: 0,
      currency: 'EUR',
      exchangeRate: 1.0,
      notes: 'Posició consolidada de fons'
    },
    {
      id: 't_init_fons_2',
      date: '2025-12-01',
      type: 'compra',
      assetType: 'fons',
      isin: 'ES0174013021',
      symbol: 'CRE-RF',
      name: 'CREAND RTA. FIXA MIXTA',
      quantity: 1,
      price: 130094.00,
      commission: 0,
      currency: 'EUR',
      exchangeRate: 1.0,
      notes: 'Posició consolidada de fons'
    },
    {
      id: 't_init_fons_3',
      date: '2025-12-01',
      type: 'compra',
      assetType: 'fons',
      isin: 'IE00B3K83P04',
      symbol: 'POL-HE',
      name: 'POLAR CAP-HEALTH',
      quantity: 1,
      price: 93312.00,
      commission: 0,
      currency: 'EUR',
      exchangeRate: 1.0,
      notes: 'Posició consolidada de fons'
    },
    {
      id: 't_init_fons_4',
      date: '2025-12-01',
      type: 'compra',
      assetType: 'fons',
      isin: 'IE00B03HCZ61',
      symbol: 'VAN-GL',
      name: 'VANG,GLOB, STK',
      quantity: 1,
      price: 622938.00,
      commission: 0,
      currency: 'EUR',
      exchangeRate: 1.0,
      notes: 'Posició consolidada de fons'
    },
    {
      id: 't_init_fons_5',
      date: '2025-12-01',
      type: 'compra',
      assetType: 'fons',
      isin: 'IE0031786142',
      symbol: 'VAN-EM',
      name: 'VANG-EMRG IND',
      quantity: 1,
      price: 123432.00,
      commission: 0,
      currency: 'EUR',
      exchangeRate: 1.0,
      notes: 'Posició consolidada de fons'
    },
    {
      id: 't_init_fons_6',
      date: '2025-12-01',
      type: 'compra',
      assetType: 'fons',
      isin: 'LU0384405600',
      symbol: 'VON-CL',
      name: 'VONT,CLE,TECHN',
      quantity: 1,
      price: 67982.00,
      commission: 0,
      currency: 'EUR',
      exchangeRate: 1.0,
      notes: 'Posició consolidada de fons'
    },
    {
      id: 't_init_fons_7',
      date: '2025-12-01',
      type: 'compra',
      assetType: 'fons',
      isin: 'LU0171307068',
      symbol: 'BGF-WH',
      name: 'BGF WORLD HEALT',
      quantity: 1,
      price: 67603.00,
      commission: 0,
      currency: 'EUR',
      exchangeRate: 1.0,
      notes: 'Posició consolidada de fons'
    },
    {
      id: 't_init_fons_8',
      date: '2025-12-01',
      type: 'compra',
      assetType: 'fons',
      isin: 'LU0232524495',
      symbol: 'AB-AM',
      name: 'AB-AMER, GROW,',
      quantity: 1,
      price: 104445.00,
      commission: 0,
      currency: 'EUR',
      exchangeRate: 1.0,
      notes: 'Posició consolidada de fons'
    },
    {
      id: 't_init_fons_9',
      date: '2025-12-01',
      type: 'compra',
      assetType: 'fons',
      isin: 'LU1295551144',
      symbol: 'CAP-NP',
      name: 'CAP,GR,NEW PER',
      quantity: 1,
      price: 131406.00,
      commission: 0,
      currency: 'EUR',
      exchangeRate: 1.0,
      notes: 'Posició consolidada de fons'
    },
    {
      id: 't_init_fons_10',
      date: '2025-12-01',
      type: 'compra',
      assetType: 'fons',
      isin: 'LU0034353002',
      symbol: 'DWS-FR',
      name: 'DWS FLOAT RATE NOTS',
      quantity: 1,
      price: 251265.00,
      commission: 0,
      currency: 'EUR',
      exchangeRate: 1.0,
      notes: 'Posició consolidada de fons'
    },
    {
      id: 't_init_fons_11',
      date: '2025-12-01',
      type: 'compra',
      assetType: 'fons',
      isin: 'LU0145476817',
      symbol: 'GEN-IB',
      name: 'GENERALI INVEST. BOND',
      quantity: 1,
      price: 243512.00,
      commission: 0,
      currency: 'EUR',
      exchangeRate: 1.0,
      notes: 'Posició consolidada de fons'
    },
    {
      id: 't_init_fons_12',
      date: '2025-12-01',
      type: 'compra',
      assetType: 'fons',
      isin: 'LU0113257694',
      symbol: 'SIS-CB',
      name: 'SISF EUR CORPORATE BOND',
      quantity: 1,
      price: 86841.00,
      commission: 0,
      currency: 'EUR',
      exchangeRate: 1.0,
      notes: 'Posició consolidada de fons'
    },
    {
      id: 't_init_fons_13',
      date: '2025-12-01',
      type: 'compra',
      assetType: 'fons',
      isin: 'LU1670724373',
      symbol: 'MG-OI',
      name: 'M&G OPTIMAL INCOME',
      quantity: 1,
      price: 51875.80,
      commission: 0,
      currency: 'EUR',
      exchangeRate: 1.0,
      notes: 'Posició consolidada de fons'
    },
    {
      id: 't_init_fons_14',
      date: '2025-12-01',
      type: 'compra',
      assetType: 'fons',
      isin: 'LU0599946893',
      symbol: 'DWS-CK',
      name: 'DWS CONCEPT KALDEMORG',
      quantity: 1,
      price: 88330.00,
      commission: 0,
      currency: 'EUR',
      exchangeRate: 1.0,
      notes: 'Posició consolidada de fons'
    },
    {
      id: 't_init_fons_15',
      date: '2025-12-01',
      type: 'compra',
      assetType: 'fons',
      isin: 'IE00B4468526',
      symbol: 'POL-TE',
      name: 'POLAR CAP. GL TECH.R EUR',
      quantity: 1,
      price: 167268.00,
      commission: 0,
      currency: 'EUR',
      exchangeRate: 1.0,
      notes: 'Posició consolidada de fons'
    },
    {
      id: 't_init_fons_16',
      date: '2025-12-01',
      type: 'compra',
      assetType: 'fons',
      isin: 'LU0515768454',
      symbol: 'THR-ND',
      name: 'THREADNEEDLE',
      quantity: 1,
      price: 105020.00,
      commission: 0,
      currency: 'EUR',
      exchangeRate: 1.0,
      notes: 'Posició consolidada de fons'
    },
    {
      id: 't_init_fons_17',
      date: '2025-12-01',
      type: 'compra',
      assetType: 'fons',
      isin: 'LU0203975437',
      symbol: 'ROB-GP',
      name: 'ROBECO GLOBAL PREMIUM',
      quantity: 1,
      price: 157490.00,
      commission: 0,
      currency: 'EUR',
      exchangeRate: 1.0,
      notes: 'Posició consolidada de fons'
    }
  ],

  // Preus de cotització "en viu" inicials reals
  livePrices: {
    'AXA-GL': { current: 126209.00, change: 0.0, currency: 'EUR' },
    'CRE-RF': { current: 130094.00, change: 0.0, currency: 'EUR' },
    'POL-HE': { current: 93312.00, change: 0.0, currency: 'EUR' },
    'VAN-GL': { current: 622938.00, change: 0.0, currency: 'EUR' },
    'VAN-EM': { current: 123432.00, change: 0.0, currency: 'EUR' },
    'VON-CL': { current: 67982.00, change: 0.0, currency: 'EUR' },
    'BGF-WH': { current: 67603.00, change: 0.0, currency: 'EUR' },
    'AB-AM': { current: 104445.00, change: 0.0, currency: 'EUR' },
    'CAP-NP': { current: 131406.00, change: 0.0, currency: 'EUR' },
    'DWS-FR': { current: 251265.00, change: 0.0, currency: 'EUR' },
    'GEN-IB': { current: 243512.00, change: 0.0, currency: 'EUR' },
    'SIS-CB': { current: 86841.00, change: 0.0, currency: 'EUR' },
    'MG-OI': { current: 51875.80, change: 0.0, currency: 'EUR' },
    'DWS-CK': { current: 88330.00, change: 0.0, currency: 'EUR' },
    'POL-TE': { current: 167268.00, change: 0.0, currency: 'EUR' },
    'THR-ND': { current: 105020.00, change: 0.0, currency: 'EUR' },
    'ROB-GP': { current: 157490.00, change: 0.0, currency: 'EUR' }
  }
};
